name: generate-ascii
on: push

jobs:
  acsii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Lest Repository Files
        run: ls -ltr

      - name: Execute script
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh