name: Build Test and Deploy

on:
    workflow_dispatch:
    push: 
    #     branches: main
    # pull_request: 
    #     branches: main
    # schedule:
    #     - cron: "*/1 * * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: build
             run: echo "Building software"
             
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: testing
              run: echo "Testing software"

    deploy:
        if: github.ref == 'refs/heads/main'
        needs: test
        concurrency: 
            group: production-deployment
            cancel-in-progress: false
        runs-on: ubuntu-latest
        steps:
            - name: deploying software
              timeout-minutes: 1
              run: |
                echo "deployng software"
                sleep 300s

