name: Workflow Filters
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - closed
    branches: 
      - main
    paths-ignore: 
      - README.md


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is executed by the event type $ {{github.event.name}}"